Compute_Device:
  available:
  database_creation: cpu
  database_query: cpu
  gpu_brand: NVIDIA
EMBEDDING_MODEL_DIMENSIONS: null
EMBEDDING_MODEL_NAME: ''
Platform_Info:
  os: windows
Supported_CTranslate2_Quantizations:
  CPU:
  GPU:
WhisperSpeech:
  model: null
bark:
  enable_cpu_offload: false
  model_precision: float16
  size: small
  speaker: v2/en_speaker_6
created_databases: {}
database:
  chunk_overlap: 250
  chunk_size: 700
  contexts: '5'
  database_to_search: ''
  document_types: ''
  half: false
  search_term: ''
  similarity: 0.8
hf_access_token:
openai:
  api_key:
  model: gpt-4o-mini
  reasoning_effort: medium
server:
  api_key: ''
  connection_str: http://localhost:1234/v1
  show_thinking: false
transcribe_file:
  device: cpu
  file: null
  model: whisper-small-en
  quant: float32
  timestamps: true
transcriber:
  device: cpu
  model: whisper-small.en
  quant: float32
tts:
  model: googletts
  s2a:
  t2s:
vision:
  chosen_model: Florence-2-base
  chosen_quant: float16
  chosen_size: 2b
  flash_attention2: null
  test_image: null